In [1]:
5+5

10

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("benroshan/factors-affecting-campus-placement")

print("Path to dataset files:", path)

Downloading to C:\Users\Admin\.cache\kagglehub\datasets\benroshan\factors-affecting-campus-placement\1.archive...

100%|██████████| 4.51k/4.51k [00:00<?, ?B/s]

Extracting files...
Path to dataset files: C:\Users\Admin\.cache\kagglehub\datasets\benroshan\factors-affecting-campus-placement\versions\1

In [4]:
df = pd.read_csv(f'{path}/Placement_Data_Full_Class.csv')

In [5]:
df.shape

(215, 15)

In [6]:
df.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [7]:
df.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [8]:
df.duplicated

<bound method DataFrame.duplicated of      sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0        1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1        2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2        3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3        4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4        5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0
..     ...    ...    ...      ...  ...             ...    ...         ...       ...
210    211      M  80.60   Others  ...         Mkt&Fin  74.49      Placed  400000.0
211    212      M  58.00   Others  ...         Mkt&Fin  53.62      Placed  275000.0
212    213      M  67.00   Others  ...         Mkt&Fin  69.72      Placed  295000.0
213    214      F  74.00   Others  ...          Mkt&HR  60.23      Placed  204000.0
214    215      M  62.00  Central  ...          Mkt&HR  60.22  Not Placed       NaN

[215 rows x 15 columns]>

In [9]:
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [10]:
df = df.drop(columns = ['sl_no'])
df = df.drop(columns = ['salary'])

In [11]:
df.head()

  gender  ssc_p    ssc_b  hsc_p  ... etest_p specialisation  mba_p      status
0      M  67.00   Others  91.00  ...    55.0         Mkt&HR  58.80      Placed
1      M  79.33  Central  78.33  ...    86.5        Mkt&Fin  66.28      Placed
2      M  65.00  Central  68.00  ...    75.0        Mkt&Fin  57.80      Placed
3      M  56.00  Central  52.00  ...    66.0         Mkt&HR  59.43  Not Placed
4      M  85.80  Central  73.60  ...    96.8        Mkt&Fin  55.50      Placed

[5 rows x 13 columns]

In [33]:
OBJ = LabelEncoder()
df['gender'] = OBJ.fit_transform(df['gender'])
df['ssc_b'] = OBJ.fit_transform(df['ssc_b'])
df['ssc_p'] = OBJ.fit_transform(df['ssc_p'])
df['hsc_b'] = OBJ.fit_transform(df['hsc_b'])
df['hsc_p'] = OBJ.fit_transform(df['hsc_p'])
df['hsc_b'] = OBJ.fit_transform(df['hsc_b'])
df['degree_p'] = OBJ.fit_transform(df['degree_p'])
df['degree_t'] = OBJ.fit_transform(df['degree_t'])
df['workex'] = OBJ.fit_transform(df['workex'])
df['etest_p'] = OBJ.fit_transform(df['etest_p'])
df['mba_p'] = OBJ.fit_transform(df['mba_p'])
df['specialisation'] = OBJ.fit_transform(df['specialisation'])
df['status'] = OBJ.fit_transform(df['status'])
df['hsc_s'] = OBJ.fit_transform(df['hsc_s'])

In [34]:
df.columns

Index(['gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s', 'degree_p',
       'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p', 'status'],
      dtype='object')

In [35]:
X = df[['gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s', 'degree_p',
       'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p']]
y = df['status']

In [36]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.2 , random_state = 42)

In [37]:
df.head()

   gender  ssc_p  ssc_b  hsc_p  ...  etest_p  specialisation  mba_p  status
0       1     46      1     93  ...        9               1     64       1
1       1     82      0     79  ...       74               0    153       1
2       1     42      0     51  ...       55               0     50       1
3       1     22      0     14  ...       37               1     72       0
4       1     98      0     70  ...       96               0     28       1

[5 rows x 13 columns]

In [38]:
model = DecisionTreeClassifier()

model.fit(x_train, y_train)

DecisionTreeClassifier()

In [40]:
predict = model.predict(x_test)
predict

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [43]:
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test, predict)
print("Accuracy:", score)

Accuracy: 0.8372093023255814

In [44]:
import pickle

pickle.dump(model, open('DecisionTree.pkl', 'wb'))
print('PKL File Created Successfully')

PKL File Created Successfully